on:
  push:
    branches:
      - master

name: Publish typed_json_dataclass
jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: install
      - name: Run flake8
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args:
            run python -m flake8 --show-source --import-order-style pep8 typed_json_dataclass
            tests
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/pyproject.lock') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-
      - name: Install
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args:
            run python -m pytest --cov-report xml:codecov.xml --cov=typed_json_dataclass
            --cov-report=html --junit-xml=coverage.xml --cov-branch --cov-fail-under=100
            tests/
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [flake8, pytest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/pyproject.lock') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-
      - name: Install
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: install
      - name: Upload codecov
        uses: abatilo/actions-poetry@v1.9.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: '"run codecov -t $CODECOV_TOKEN"'
      - name: Publish
        uses: abatilo/actions-poetry@v1.9.0
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args:
            publish --build --no-interaction -vv --username $PYPI_USERNAME --password
            $PYPI_PASSWORD
